### ISSUE TITLE
current 1.0 release does not include Makefile

### ISSUE THREAD

**Issue by chouellaine** [e-jorsboe/fastNGSadmix#10]
Hi! Could we get an updated release that includes the Makefile so that we could properly build the software in Docker? 

Thank you!

**Comment by e-jorsboe** [comment]
I have added a Dockerfile, that should make it able to be built in Docker.

**Comment by chouellaine** [comment]
Appreciate it! Would it be possible to push a new release? I'd like to be able to use a fixed version of the software to better document and share the dependencies with others.

**Comment by e-jorsboe** [comment]
I have made a version 1.1.

**Comment by chouellaine** [comment]
This is greatly appreciated, thank you!
