### ISSUE TITLE
no output ?

### ISSUE THREAD

**Issue by zyxplus** [e-jorsboe/fastNGSadmix#2]
what should I do with 'This many sites in ref are either not-valid-number or below maf in any of the chosen pops 0'?

**Comment by e-jorsboe** [comment]
Hi,

It means that there 0 invalid sites in the reference panel. Invalid sites are either non-numeric values in any of the chosen population, like for example "NA" or sites that are below the MAF threshold in any of the selected populations, the default MAF threshold is 0.00.

So I do not see a problem with this?

**Comment by zyxplus** [comment]
Sorry to ask a naive question. I am new to admixture analysis. So given the published SNP data, for example 500 people from different population, I should first filter out those locus (MAF < 0.05, missingness >0.01) then LD_pruning, is there some important steps I didn't take? (I did the missingness filter and LD_pruning though). I think, no valid loci is such a rare condition, how could that happen?

**Comment by e-jorsboe** [comment]
So is your problem that you have no sites in your reference panel? (Which might be because you inadvertently removed them all during your filtering)

Or is your problem that you have no non-valid sites? And if so, why is that a problem?

What is your overlap when doing the analysis?

**Comment by zyxplus** [comment]
My problem is no non-valid sites. Do I need to find out overlap loci first then ran admixture ,last fastNGSadmix?

**Comment by e-jorsboe** [comment]
Why is that a problem non-valid sites, will be discarded from the analysis as they are not valid.

fastNGSadmix will find the overlapping sites between your reference panel and your input sample.

What is the output you get when you run fastNGSadmix?

**Comment by e-jorsboe** [comment]
Can I close this issue?
